datapull:
  application:
    region:
  secretstore:
    vault:
      vault_url:
      static_secret_path_prefix:
      vault_nonce:
      vault_path_login:
  json:
    inputjson: Input_Sample_filesystem-to-filesystem.json
  spark:
    network: spark.network.timeout
    timeout: 10000s
    executor: spark.executor.heartbeatInterval
    interval: 1000s
    broadcasttimeout: spark.sql.broadcastTimeout
    btimeout: 36000
    scheduler: spark.scheduler.mode
    mode: FAIR
    failures: spark.task.maxFailures
  miscellaneous:
    no_of_retries: 16
    timeout: 10000
    consul_url:
    sleeptimeout: 60000
  api:
    s3_bucket_name:
    application_subnet_1:
    application_subnet_2:
    application_security_group:
    vpc_id:
    load_balancer_certificate_arn:
  emr:
    emr_security_group_master:
    emr_security_group_slave:
    emr_security_group_service_access:
    hive_properties:
      hive.metastore.uris:
      hive.security.authorization.createtable.role.grants:
      hive.metastore.client_socket.timeout:
      hive.security.authorization.manager:
      hive.exec.max.dynamic.partitions:
      hive.exec.max.dynamic.partitions.pernode:
      hive.exec.compress.output:
      hive.optimize.sort.dynamic.partition:
      hive.metastore.filter.hook:
      mapreduce.map.java.opts:
      mapreduce.map.memory.mb:
      tez.am.resource.memory.mb:
      hive.tez.container.size:
      parquet.compression:
    spark_hive_properties:
      hive.metastore.uris:git
    tags:
      Brand:
      Category: EMRPipeline
      Owner:
      Purpose: EMRPipeline
      Service: emr
      Platform: EMRPipeline
  logger:
    cloudwatch:
      groupName: /ecs/datatools-datapull-api
      streamName: datapull-stream
    mssql:
      server:
      database:
      login:
      password:
      table:
      driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  email:
    smtp:
      emailaddress:
      smtpserveraddress:
    ses:
      region:
      email:
      access_key:
      secret_key:
