site_name: DataPull Documentation
site_description: 'Open Source Docs and Community Standards'
site_author: 'Data Tools'
site_url: 'https://homeaway.github.io/datapull'
repo_name: 'homeaway/datapull'
repo_url: 'https://github.com/homeaway/datapull/'
edit_uri: 'edit/master/docs/docs/'
theme:
    name: material
nav:
    - Home: index.md
    - Architecture: architecture.md
    - DataPull on AWS:
        - Installing DataPull on AWS Fargate and S3: install_on_aws.md
        - Setup VPC etc. in AWS Account for DataPull install: aws_account_setup.md
        - Running DataPull on AWS EMR: emr_runbook.md
        - Custom EC2 Role for EMR: custom_emr_ec2_role.md
        - Uninstalling DataPull on AWS Fargate and S3: uninstall_on_aws.md
    - Support for Oracle and Teradata: oracle_teradata_support.md
    - Access secrets: access_secrets.md
    - Sample input JSON:
        - Sample Json: transformation.md
        - Fetching Existing Json: fetching_existing_json.md
    - Monitor DataPull jobs using Spark UI: monitor_spark_ui.md
    - FAQs: faq.md