site_name: DataPull Documentation
site_description: 'Open Source Docs and Community Standards'
site_author: 'Data Tools'
site_url: 'https://homeaway.github.io/datapull'
repo_name: 'homeaway/datapull'
repo_url: 'https://github.com/homeaway/datapull/'
edit_uri: 'edit/master/docs/docs/'
theme:
    name: material
nav:
    - Home: index.md
    - Architecture: architecture.md
    - Installing DataPull on AWS Fargate and S3: install_on_aws.md
    - Setup VPC etc. in AWS Account for DataPull install: aws_account_setup.md
    - Add support for Oracle and Teradata: oracle_teradata_support.md
    - Running DataPull on AWS EMR: emr_runbook.md
    - Sample input JSON: transformation.md
    - FAQs: faq.md